### ISSUE TITLE
Swift Package Manager requires x.y.z version number

### ISSUE THREAD

**Issue by Dean151** [florianbuerger/InterfaceBacked#3]
SPM expect x.y.z version number.
Current version is 2.4 ; it should be 2.4.0.
Currently, the most recent version SPM can see is 2.2.1 ; that does not contains the Package.swift file.

Fix is simple : simply tag 63314f0e799abbf0d69834d25a6da51a73fd91c4 with "2.4.0" will seamlessly make everything back into order.

**Comment by florianbuerger** [comment]
Whoops 🤦 Fixed. Thanks for catching it.

**Comment by Dean151** [comment]
No problem, thanks! :)
